// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0gopg9ws14MR2rGFiRQcbqiYCASTuZ7s',
    appId: '1:374798822563:web:da8e334983ab49e41a6316',
    messagingSenderId: '374798822563',
    projectId: 'fitness-mob-app',
    authDomain: 'fitness-mob-app.firebaseapp.com',
    storageBucket: 'fitness-mob-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr5ikGsGCqneelbHEnsMAJfOZKOQsVwU8',
    appId: '1:374798822563:android:d795e5688743d42c1a6316',
    messagingSenderId: '374798822563',
    projectId: 'fitness-mob-app',
    storageBucket: 'fitness-mob-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0rtxWB-mnrZZwlpBwacvgqFiVYGGQ5lw',
    appId: '1:374798822563:ios:88cccfcf665a74611a6316',
    messagingSenderId: '374798822563',
    projectId: 'fitness-mob-app',
    storageBucket: 'fitness-mob-app.appspot.com',
    iosClientId: '374798822563-f0clnh303d0rclv2lhc0gjn5p5ij5ldb.apps.googleusercontent.com',
    iosBundleId: 'com.ammarjaved.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0rtxWB-mnrZZwlpBwacvgqFiVYGGQ5lw',
    appId: '1:374798822563:ios:88cccfcf665a74611a6316',
    messagingSenderId: '374798822563',
    projectId: 'fitness-mob-app',
    storageBucket: 'fitness-mob-app.appspot.com',
    iosClientId: '374798822563-f0clnh303d0rclv2lhc0gjn5p5ij5ldb.apps.googleusercontent.com',
    iosBundleId: 'com.ammarjaved.fitness',
  );
}
